In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,3,4,3,5])
print(a[1:])

print(a[a<3])

print(np.empty(4))     #made random number

#np.arange(first num , last num , step )
print(np.arange(1,100,5))

#np.arange(first num , last num , how many number write?)
print(np.linspace(0 , 10 , 5))

b = [12,3,43,2,1,0]
print(np.sort(b))

a = [12,2,2,2,2,456,78,5,56,788]
print(np.concatenate((a,b)))

[2 3 4 3 4 3 5]
[1 2]
[6.95278925e-310 1.06523319e-311 1.06520339e-311 1.06520339e-311]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[ 0.   2.5  5.   7.5 10. ]
[ 0  1  2  3 12 43]
[ 12   2   2   2   2 456  78   5  56 788  12   3  43   2   1   0]


In [5]:
 
c = np.array(([1,2] , [3,4]))
d = np.array(([5,6] , [7,8]))
print(np.concatenate((c,d) , axis=0))
print(np.concatenate((c,d) , axis=1))





[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [6]:
aa = np.array([[[1, 2, 5, 6],
 [3, 4, 7, 8]] ,[[1, 2, 5, 6],
 [3, 4, 7, 8]] ,[[1, 2, 5, 6],
 [3, 4, 7, 8]]])
print(aa.ndim)
print(aa.size)
print(aa.shape)


3
24
(3, 2, 4)


In [7]:
zr = np.zeros((5,5))
print(zr)

oner = np.ones((4,3))
print(oner)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:


q = np.array([1,3,5,6,54,6,4,5,4,5])
w = np.array([53,5,5,3,5,9,5,3,5,3])

print('q.w = ' , np.dot(q,w))  #dot product
print(q@w)    #dot product

print(q*w)    #zarbe moalefeii
print(np.multiply(q,w))  #zarbe moalefeii

q.w =  505
505
[ 53  15  25  18 270  54  20  15  20  15]
[ 53  15  25  18 270  54  20  15  20  15]


In [9]:
print(np.subtract(q,w))   #tafrigh do matrix

[-52  -2   0   3  49  -3  -1   2  -1   2]


In [10]:
print(np.divide(q,3))   #taghsim arayeh ha bar 3

[ 0.33333333  1.          1.66666667  2.         18.          2.
  1.33333333  1.66666667  1.33333333  1.66666667]


In [12]:
ss = np.random.uniform(1,0,(5,5))    #matrix 5*5 beine 1 va 0
print(ss)

[[0.99949104 0.86327329 0.52592411 0.64462836 0.34036402]
 [0.18482308 0.04727598 0.67837342 0.95353989 0.28738846]
 [0.49603653 0.27421456 0.32668346 0.23607436 0.5465544 ]
 [0.20079408 0.48155873 0.18079277 0.48519439 0.49322463]
 [0.71690258 0.47691774 0.79882763 0.3833113  0.16722654]]


In [14]:
print(np.random.standard_normal((5,5)))     #adad tasadofi entekhabi az norm normal


[[-0.24347422  1.10566337 -1.12562489 -0.08031723 -0.48734682]
 [ 0.9127172  -1.27333825 -2.0990407  -0.84966406 -0.7790779 ]
 [-0.75368421 -1.02366041  0.34804777  0.72102963 -1.51295723]
 [-0.19563553  2.06311861 -1.42179189 -1.38672551 -0.4907334 ]
 [ 1.15877084 -1.8559213   0.42370778  0.138397   -0.07253445]]


In [15]:
print(np.unique(q))     #arayeh haye tekrari ra hazf mikonad

[ 1  3  4  5  6 54]


In [25]:
a = np.array([[1,2,3,4,5,6,7,1]])
b = np.array([[1,2,1,2,1,2,1,2,1,2,19]])
print(np.union1d(a,b))    #ejtema
print(np.intersect1d(a,b))  #eshterak

[ 1  2  3  4  5  6  7 19]
[1 2]


In [29]:
print(np.var(a))    #variance a
print(np.cov(a))    #covarians a
print(np.median(a)) #mianeh
print(np.mean(a))   #miangin

4.484375
5.125
3.5
3.625


In [32]:
a =np.array( [[1,2],
     [3,4],
     [5,6]])
print(a.max(axis=1))
print(a.max(axis=0))

[2 4 6]
[5 6]


In [41]:
z = np.array([[1],[7],[9],[1],[2],[3],[6],[4],[2],[9]])
print(z.reshape(5,2))

zz=z.transpose()
print(zz)   

print(np.flip(zz))   #mohtaviate araye ro ax mikonad

print(z.flatten())   #z.ravel()     #matrix ra yek bodi mikonad

[[1 7]
 [9 1]
 [2 3]
 [6 4]
 [2 9]]
[[1 7 9 1 2 3 6 4 2 9]]
[[9 2 4 6 3 2 1 9 7 1]]
[1 7 9 1 2 3 6 4 2 9]


In [1]:
help(max)
max?

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method